base_url = "https://lopes.id"
theme    = "kita"

title       = "Lopes' Logbook"
description = "Chronicles of my bold journey through Infosec and beyond realms."
author      = "José Lopes"


default_language   = "en"
compile_sass       = true
generate_feed      = true
feed_filename      = "atom.xml"
build_search_index = false

taxonomies = [
  {name="tags", rss=true},
]


[markdown]
highlight_code  = true
highlight_theme = "base16-ocean-dark"
extra_syntaxes_and_themes = []


[extra.style]
# bg_color          = ""
# bg_dark_color     = ""
# header_blur       = true
# header_color      = ""
# header_dark_color = ""


[extra.profile]
name          = "José Lopes"
bio           = "Infosec Engineer working with Threat Detection, boldly following his own journey."
avatar_url    = "./icons/github.svg"
avatar_invert = true

[[extra.profile.social]]
name = "github"
url = "https://github.com/lopes"

[[extra.profile.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/jlopesjr"

[[extra.profile.social]]
name = "rss"
url  = "$BASE_URL/atom.xml"

[[extra.menu]]
name = "tags"
url  = "$BASE_URL/tags"

[[extra.menu]]
name = "archive"
url  = "$BASE_URL/archive"

[[extra.menu]]
name = "projects"
url  = "$BASE_URL/projects"

[[extra.menu]]
name = "about"
url  = "$BASE_URL/about"

[extra.footer]
since       = 2020
license     = "CC BY-SA 4.0"
license_url = "https://creativecommons.org/licenses/by-sa/4.0/deed"
