[build]
  publish = "public"
  command = "zola build"

[build.environment]
  ZOLA_VERSION = "0.17.2"

[context.deploy-preview]
  command = "zola build --base-url $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-control = "no-store"