[[project]]
name = "AES in CBC Mode"
desc = "Simple implementation of AES in Chain Block Cipher mode"
tags = ["cryptography", "development"]
links = [
    { name = "github", url = "https://gist.github.com/lopes/168c9d74b988391e702aac5f4aa69e41" },
]

[[project]]
name = "NetBox Scanner"
desc = "Python program that scans subnets and adds the findings in NetBox"
tags = ["networking", "nmap", "netbox"]
links = [
    { name = "github", url = "https://github.com/lopes/netbox-scanner" },
]

[[project]]
name = "Dotfiles"
desc = "My personal configuration files."
tags = ["unix", "setup"]
links = [{ name = "github", url = "https://github.com/lopes/dotfiles" }]

[[project]]
name = "Lobotomy"
desc = "Script that connects to Cortex XDR API and retrieves the alerts"
tags = ["development", "api", "cortex"]
links = [
    { name = "github", url = "https://gist.github.com/lopes/964d95e4c530e6f7c8982228be21572c" },
]
